# supabase/config.toml

# Configurações gerais do projeto Supabase
project_id = "zzugbgoylwbaojdnunuz"

[api]
# Porta da API local
port = 54321
# Esquemas a serem expostos na API
schemas = ["public", "storage", "graphql"]
# Limite máximo de linhas que podem ser retornadas em uma única consulta
max_rows = 1000

[db]
# Porta do banco de dados local
port = 54322
# Usar o Major Version do Postgres que o Supabase usa.
major_version = 15

[studio]
# Porta do Supabase Studio local
port = 54323

# Configuração de funções (Edge Functions)
[functions]
  # Configuração para a função 'trial-reminder'
  [functions.trial-reminder]
    # Rota do handler da função
    handler = "file://./supabase/functions/trial-reminder/index.ts"
    # Política de verificação de JWT
    verify_jwt = false
    # Agendamento da execução (cron-like), corrigido de 'cron' para 'schedule'
    # Executa todo dia à 1h da manhã (UTC)
    schedule = "0 1 * * *"

  # Configuração para a função 'evolution-webhook'
  [functions.evolution-webhook]
    # Rota do handler da função
    handler = "file://./supabase/functions/evolution-webhook/index.ts"
    # Política de verificação de JWT
    verify_jwt = false

  # Configuração para a função 'ia-coach-chat'
  [functions.ia-coach-chat]
    # Rota do handler da função
    handler = "file://./supabase/functions/ia-coach-chat/index.ts"
    # Política de verificação de JWT
    verify_jwt = true # Requer autenticação
