# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "zzugbgoylwbaojdnunuz"  # substitua depois com 'xyz...' do seu Supabase

[api]
# Porta da API local
port = 54321
# Esquemas a serem expostos na API
schemas = ["public", "storage", "graphql"]
# Limite máximo de linhas que podem ser retornadas em uma única consulta
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54328
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
# Porta do Supabase Studio local
port = 54323

# Configuração de funções (Edge Functions)
[functions]
  # Configuração para a função 'trial-reminder'
  [functions.trial-reminder]
    entrypoint = "./functions/trial-reminder/index.ts"
    verify_jwt = false

  # Configuração para a função 'evolution-webhook'
  [functions.evolution-webhook]
    entrypoint = "./functions/evolution-webhook/index.ts"
    verify_jwt = false

  # Configuração para a função 'ia-coach-chat'
  [functions.ia-coach-chat]
    entrypoint = "./functions/ia-coach-chat/index.ts"
    verify_jwt = false # Desabilitado para permitir validação customizada via INTERNAL_FUNCTION_SECRET (mais adequada para server-to-server)

  # Configuração para a função 'generate-plan'
  [functions.generate-plan]
    entrypoint = "./functions/generate-plan/index.ts"
    verify_jwt = false # Permite chamadas internas autenticadas via service role key
