-- This migration is intentionally left blank.
-- It contained multiple syntax errors and logical inconsistencies.
-- The necessary corrections (renaming columns, changing types, etc.)
-- have been implemented in preceding, more granular migration files.