-- Cria a tabela para rastrear o envio de notificações de lembrete de trial.
CREATE TABLE IF NOT EXISTS public.trial_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    notification_type TEXT NOT NULL, -- ex: 'trial_expiring_3_days', 'trial_expired'
    sent_at TIMESTAMPTZ DEFAULT timezone('UTC', now()),
    created_at TIMESTAMPTZ DEFAULT timezone('UTC', now()),
    CONSTRAINT uq_user_notification_type UNIQUE (user_id, notification_type)
);

-- Adiciona um comentário para descrever o propósito da tabela.
COMMENT ON TABLE public.trial_notifications IS 'Registra as notificações enviadas aos usuários durante o período de trial para evitar duplicidade.';

-- Habilita RLS na tabela.
ALTER TABLE public.trial_notifications ENABLE ROW LEVEL SECURITY;

-- Permite que usuários acessem suas próprias notificações (se necessário no futuro).
CREATE POLICY "Users can view their own notifications" ON public.trial_notifications
    FOR SELECT USING (auth.uid() = user_id);

-- Permite que o serviço (usando a service_role key) insira registros.
-- A inserção será feita pela Edge Function, que usa a chave de serviço.
