-- This migration is intentionally left blank as it was conceptually incorrect.
-- It attempted to apply RLS to a view, and did so before the view was created.
-- The correct RLS policies are handled in a later migration (20250917010000_fix_security_issues.sql).