-- This migration is intentionally left blank.
-- It contained a syntax error for index creation (casting with ::date).
-- A preceding migration (20250915135959_fix_index_creation.sql) creates the index correctly.