name: supabase-migrate-prod
on:
  push: { branches: ["main"] }
  workflow_dispatch: {}
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v2
        with: { version: latest }

      # login NÃO interativo com o token do Secret
      - name: Supabase login (non-interactive)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Link project
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: supabase link --project-ref "$SUPABASE_PROJECT_REF"

      - name: Apply migrations
        run: supabase db push

      - name: Show status
        run: supabase db status
