name: supabase-migrate-prod-cli
on:
  push: { branches: ["main"] }
  workflow_dispatch: {}

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Supabase CLI
        shell: bash
        run: |
          curl -fsSL https://cli.supabase.com/install | sh
          echo "$HOME/.supabase/bin" >> $GITHUB_PATH
          which supabase
          supabase --version

      - name: Supabase login (non-interactive)
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Link project
        run: supabase link --project-ref "$SUPABASE_PROJECT_REF"

      - name: Apply migrations
        run: supabase db push

      - name: Show status
        run: supabase db status
