name: supabase-migrate-prod
on:
  push: { branches: ["main"] }
  workflow_dispatch: {}

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

    steps:
      - uses: actions/checkout@v4

      # >>> versão correta da action
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabase login (non-interactive)
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Link project
        run: supabase link --project-ref "$SUPABASE_PROJECT_REF"

      - name: Apply migrations
        run: supabase db push

      - name: Show status
        run: supabase db status
